blank_issues_enabled: true
- name: 💬 Come chat with our boisterous and helpful community and devs
  url: https://discord.gg/TzPVK8fNBm
  about: Over 2000 people are chatting in Discord and you could be next
